// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enlpugyqiitjycedpdya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVubHB1Z3lxaWl0anljZWRwZHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDIxNzcsImV4cCI6MjA2NTIxODE3N30.p7CJrC69qA3jhly5RwfWRgR0M5On-7jt7AxurzxucwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);